version: "3"
services:
#  database:
#    container_name: mysql
#    image: mysql:8.0.28
#    environment:
#      MYSQL_DATABASE: userdb
#      MYSQL_USER: user
#      MYSQL_PASSWORD: userpwd
#      MYSQL_ROOT_HOST: '%'
#      MYSQL_ROOT_PASSWORD: rootpwd
#    ports:
#      - "3306:3306"
#    networks:
#      - dev_network

  application:
    build: .
#    depends_on:
#      - database
    ports:
      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/userdb
#      SPRING_DATASOURCE_USERNAME: user
#      SPRING_DATASOURCE_PASSWORD: userpwd
    networks:
      - dev_network

networks:
  dev_network:

