name: Create Release

# on:
#   push:
#     tags:
#       - '*'
on:
  push:
    branches: [ "main" ]

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # with:
        #   fetch-depth: 0 # fetch all history for all tags and branches

      - name: Create changelog text
        id: changelog
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ secrets.MY_TOKEN }}
          config_file: .github/tag-changelog-config.js
          # exclude_types: other,doc,chore

      - name: Create release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.changelog.outputs.changes }}
          previous_release: v1.0.0
